version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ./projet:/app
      - ./docker/000-default.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - '8000:80'
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
  adminer:
    depends_on:
      - db
    image: adminer:latest
    ports:
      - 8201:8080
